import { normalizeStories } from './src/data.js';

const FEED_KEY = '4.0-news-feed-v1';
const LEGACY_FEED_KEY = 'signal-news-feed-v2';
const FOLDERS_KEY = '4.0-news-folders-v1';
const READING_KEY = '4.0-news-reading-v1';
const app = document.querySelector('#app');
const toastRegion = document.querySelector('#toast-region');
const savedReading = load(READING_KEY, {});
const state = {
  feed: load(FEED_KEY, load(LEGACY_FEED_KEY, [])), folders: load(FOLDERS_KEY, []), activeFolder: 'all',
  view: 'library', selectedStoryId: null, readerTheme: savedReading.theme || 'paper',
  fontScale: savedReading.fontScale || 1, newStoryIds: [], webmcp: { supported: false, registered: 0 },
};
let toolsRegistered = false;

function load(key, fallback) { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } }
function save() { localStorage.setItem(FEED_KEY, JSON.stringify(state.feed)); localStorage.setItem(FOLDERS_KEY, JSON.stringify(state.folders)); localStorage.setItem(READING_KEY, JSON.stringify({ theme: state.readerTheme, fontScale: state.fontScale })); }
function escapeHtml(value = '') { return String(value).replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]); }
function safeUrl(value) { try { const url = new URL(value); return ['http:', 'https:'].includes(url.protocol) ? url.href : '#'; } catch { return '#'; } }
function date(value, options = { month: 'short', day: 'numeric', year: 'numeric' }) { const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? 'Recently' : new Intl.DateTimeFormat('en-US', options).format(parsed); }
function today() { return new Intl.DateTimeFormat('en-US', { weekday: 'long', month: 'long', day: 'numeric' }).format(new Date()); }
function keyFor(value) { return String(value).trim().toLocaleLowerCase().replace(/\s+/g, ' ').slice(0, 60); }
function titleFor(value) { return String(value).trim().replace(/\s+/g, ' ').slice(0, 60); }
function icon(name) { const icons = {
  book: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M4.5 5.5A2.5 2.5 0 0 1 7 3h11.5v16H7a2.5 2.5 0 0 0-2.5 2.5V5.5Z"/><path d="M7 3v16"/><path d="M10 7h5M10 11h5"/></svg>',
  inbox: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M4 5h16v14H4z"/><path d="M4 14h4l1.5 2h5L16 14h4"/></svg>',
  folder: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M3.5 6.5h6l1.7 2H20a1 1 0 0 1 1 1V18a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7.5a1 1 0 0 1 .5-1Z"/></svg>',
  plus: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9"><path d="M12 5v14M5 12h14"/></svg>',
  arrow: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M5 12h13M13 6l6 6-6 6"/></svg>',
  back: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M19 12H5M11 6l-6 6 6 6"/></svg>',
  moon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M20 15.2A8.4 8.4 0 0 1 8.8 4 8.5 8.5 0 1 0 20 15.2Z"/></svg>',
  sun: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><circle cx="12" cy="12" r="3.5"/><path d="M12 2.5v2M12 19.5v2M21.5 12h-2M4.5 12h-2M18.7 5.3l-1.4 1.4M6.7 17.3l-1.4 1.4M18.7 18.7l-1.4-1.4M6.7 6.7 5.3 5.3"/></svg>',
  bookmark: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M6 4.5A1.5 1.5 0 0 1 7.5 3h9A1.5 1.5 0 0 1 18 4.5V21l-6-3.6L6 21V4.5Z"/></svg>',
  dots: '<svg viewBox="0 0 24 24" fill="currentColor"><circle cx="5" cy="12" r="1.5"/><circle cx="12" cy="12" r="1.5"/><circle cx="19" cy="12" r="1.5"/></svg>',
  sparkle: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="m12 2.8 1.7 7.5 7.5 1.7-7.5 1.7-1.7 7.5-1.7-7.5-7.5-1.7 7.5-1.7L12 2.8Z"/></svg>',
}; return icons[name] || ''; }
function ensureFolder(name, curated = true) { const title = titleFor(name); const id = keyFor(title); if (!title || !id) return null; let folder = state.folders.find((entry) => entry.id === id); if (!folder) { folder = { id, name: title, curated, createdAt: new Date().toISOString() }; state.folders.unshift(folder); } return folder; }
function migrateExistingStories() { state.feed.forEach((story) => { const names = story.tagNames || story.tags || [story.folderName || story.category || 'Reading']; const tags = names.map((name) => ensureFolder(name)).filter(Boolean); story.tagIds = tags.map((tag) => tag.id); story.tagNames = tags.map((tag) => tag.name); story.folderId = story.tagIds[0] || story.folderId; story.folderName = story.tagNames[0] || story.folderName; }); save(); }
function storiesForFolder() { return state.activeFolder === 'all' ? state.feed : state.feed.filter((story) => (story.tagIds || [story.folderId]).includes(state.activeFolder)); }
function folderCount(id) { return state.feed.filter((story) => (story.tagIds || [story.folderId]).includes(id)).length; }
function faviconFor(story) { try { return `https://www.google.com/s2/favicons?domain=${encodeURIComponent(new URL(story.url).hostname)}&sz=96`; } catch { return ''; } }
function storyImage(story) { return story.imageUrl ? safeUrl(story.imageUrl) : faviconFor(story); }
function storyMeta(story) { return `<div class="story-meta"><span>${escapeHtml(story.source)}</span><i></i><span>${date(story.publishedAt)}</span></div>`; }
function cover(story, large = false) { const image = storyImage(story); const mark = escapeHtml((story.source || '?').trim().charAt(0).toUpperCase()); return `<div class="cover ${large ? 'cover-large' : ''} ${story.imageUrl ? '' : 'cover-logo'}"><span>${mark}</span>${image ? `<img src="${escapeHtml(image)}" alt="" loading="lazy" onerror="this.remove()" />` : ''}</div>`; }
function folderRow(folder) { return `<div class="folder-wrap"><button class="folder ${state.activeFolder === folder.id ? 'active' : ''}" data-action="open-folder" data-folder="${escapeHtml(folder.id)}">${icon('folder')}<span>${escapeHtml(folder.name)}</span><b>${folderCount(folder.id)}</b></button><button class="folder-menu" data-action="rename-folder" data-folder="${escapeHtml(folder.id)}" aria-label="Rename ${escapeHtml(folder.name)}">${icon('dots')}</button></div>`; }
function sidebar() { return `<aside class="sidebar"><a class="brand" href="#" data-action="open-all"><span>4.0</span><strong>reads</strong></a><div class="library-title"><span>Library</span><button data-action="new-folder" aria-label="Create shelf">${icon('plus')}</button></div><nav class="library" aria-label="Reading shelves"><button class="folder ${state.activeFolder === 'all' ? 'active' : ''}" data-action="open-all">${icon('inbox')}<span>All saved</span><b>${state.feed.length}</b></button>${state.folders.map(folderRow).join('')}</nav><div class="sidebar-spacer"></div><div class="reader"><span class="reader-mark">Y</span><div><strong>Personal library</strong><small>${state.feed.length ? 'A quiet place to return to' : 'Waiting for your first save'}</small></div></div></aside>`; }
function emptyFeed() { return `<section class="empty-feed"><div class="empty-book">${icon('book')}</div><p class="eyebrow">A blank first page</p><h2>Save something worth staying with.</h2><p>Your next researched story will arrive here as a clean, focused reading shelf.</p><span class="empty-hint">Sources, dates, and context stay attached.</span></section>`; }
function storyCard(story, index) { const isNew = state.newStoryIds.includes(story.id); return `<article class="story-card ${isNew ? 'story-arriving' : ''}" style="--arrival-index:${index}"><button class="cover-button" data-action="open-reader" data-story="${escapeHtml(story.id)}" aria-label="Open ${escapeHtml(story.title)}">${cover(story)}</button><div class="story-card-copy"><p class="story-kicker">${escapeHtml(story.folderName || story.category || 'Reading')}</p><h3>${escapeHtml(story.title)}</h3><p class="summary">${escapeHtml(story.summary)}</p><footer>${storyMeta(story)}<button class="read-link" data-action="open-reader" data-story="${escapeHtml(story.id)}">Read ${icon('arrow')}</button></footer></div></article>`; }
function continueCard(story) { return `<section class="continue-card"><div class="continue-cover">${cover(story, true)}</div><div class="continue-copy"><p class="eyebrow">Continue reading</p><h2>${escapeHtml(story.title)}</h2><p class="continue-source">${escapeHtml(story.source)} <span>·</span> ${date(story.publishedAt)}</p><p class="summary">${escapeHtml(story.summary)}</p><button class="primary-button" data-action="open-reader" data-story="${escapeHtml(story.id)}">Open story ${icon('arrow')}</button></div><div class="continue-progress"><span><b>12</b> min read</span><i><em></em></i><span>Saved today</span></div></section>`; }
function libraryView() { const stories = storiesForFolder(); const currentFolder = state.folders.find((folder) => folder.id === state.activeFolder); const heading = currentFolder ? currentFolder.name : 'All saved'; const lead = stories[0]; const rest = stories.slice(1); return `<div class="shell">${sidebar()}<main class="library-main"><header class="topbar"><span>${today()}</span><span class="page-count">${stories.length} ${stories.length === 1 ? 'story' : 'stories'}</span></header><section class="library-hero"><p class="eyebrow">Your reading shelf</p><h1>Make room for<br><em>good stories.</em></h1><p>Long-form reporting, saved with its source and ready when you are.</p></section>${lead ? continueCard(lead) : emptyFeed()}<section class="shelf-heading"><div><p class="eyebrow">${escapeHtml(heading)}</p><h2>On your shelf</h2></div><span>${stories.length ? 'Newest first' : 'Nothing saved yet'}</span></section>${rest.length ? `<section class="story-grid">${rest.map(storyCard).join('')}</section>` : lead ? `<section class="story-grid single-story">${storyCard(lead, 0)}</section>` : ''}</main><aside class="library-aside"><div class="aside-block"><p class="eyebrow">Reading rhythm</p><div class="rhythm-number">${state.feed.length}</div><p>stories saved<br>across ${state.folders.length || 0} ${state.folders.length === 1 ? 'shelf' : 'shelves'}</p></div><div class="aside-block aside-note"><span>${icon('bookmark')}</span><p>Every story keeps its original source, publication date, and a direct path back to the reporting.</p></div><div class="aside-footer">${state.webmcp.supported ? 'Ready for your next story' : 'Library ready'}</div></aside></div>`; }
function readerSections(story) { const summary = story.summary || `This story was saved from ${story.source}.`; const paragraphs = summary.split(/(?<=[.!?])\s+/).filter(Boolean); return paragraphs.length > 1 ? paragraphs : [summary]; }
function readerView(story) { const paragraphs = readerSections(story); const summary = story.summary || `This story was saved from ${story.source}.`; return `<div class="reader-page reader-theme-${state.readerTheme}" style="--reader-scale:${state.fontScale}"><header class="reader-topbar"><button class="back-button" aria-label="Back to shelf" data-action="back-to-library">${icon('back')}<span>Back to shelf</span></button><div class="reader-title">${escapeHtml(story.folderName || story.category || 'Saved story')}</div><div class="reader-tools"><button data-action="decrease-font" aria-label="Decrease text size">A−</button><button data-action="increase-font" aria-label="Increase text size">A+</button><button data-action="toggle-theme" aria-label="Toggle reading theme">${state.readerTheme === 'night' ? icon('sun') : icon('moon')}</button><a href="${escapeHtml(safeUrl(story.url))}" target="_blank" rel="noreferrer" class="source-link">Source ${icon('arrow')}</a></div></header><div class="reading-progress"><span style="width:32%"></span></div><div class="reader-layout"><aside class="reader-rail"><p class="eyebrow">In this story</p><ol><li class="active">The story</li><li>Source notes</li></ol><div class="rail-rule"></div><span class="rail-meta">${date(story.publishedAt, { month: 'long', day: 'numeric', year: 'numeric' })}</span><span class="rail-meta">12 min read</span></aside><article class="article"><p class="eyebrow">${escapeHtml(story.source)} <span class="eyebrow-dot">·</span> ${date(story.publishedAt)}</p><h1>${escapeHtml(story.title)}</h1><p class="article-dek">A source-preserved entry from ${escapeHtml(story.source)}, saved on ${date(story.publishedAt, { month: 'long', day: 'numeric', year: 'numeric' })}.</p><div class="article-rule"></div><div class="article-body"><p class="dropcap">${escapeHtml(paragraphs[0])}</p>${paragraphs.slice(1).map((paragraph) => `<p>${escapeHtml(paragraph)}</p>`).join('')}<h2>Source notes</h2><p>This entry is preserved with its original publication date and source. Read the full reporting at <a href="${escapeHtml(safeUrl(story.url))}" target="_blank" rel="noreferrer">${escapeHtml(story.source)}</a>.</p></div><footer class="article-footer"><button data-action="back-to-library">${icon('back')} Back to shelf</button><a href="${escapeHtml(safeUrl(story.url))}" target="_blank" rel="noreferrer">Read original ${icon('arrow')}</a></footer></article><aside class="reader-side"><div class="reader-cover">${cover(story, true)}</div><p class="side-label">Saved in</p><strong>${escapeHtml(story.folderName || story.category || 'All saved')}</strong><div class="side-rule"></div><button class="side-action">${icon('bookmark')} Saved to shelf</button><p class="side-caption">A clean copy with the source kept close.</p></aside></div></div>`; }
function render() { const story = state.feed.find((entry) => entry.id === state.selectedStoryId); if (state.view === 'reader' && story) app.innerHTML = readerView(story); else { state.view = 'library'; app.innerHTML = libraryView(); } }
function toast(message) { const element = document.createElement('div'); element.className = 'toast'; element.textContent = message; toastRegion.append(element); setTimeout(() => element.remove(), 2800); }
function injectNews(topic, stories, mode = 'replace') { const normalized = normalizeStories(topic, stories); if (!normalized.length) throw new Error('No valid stories were supplied. Each story needs a title, source, and https URL.'); const enriched = normalized.map((story) => { const names = story.tags?.length ? story.tags : [story.category || topic]; const tags = names.map((name) => ensureFolder(name, true)).filter(Boolean); return { ...story, tagIds: tags.map((tag) => tag.id), tagNames: tags.map((tag) => tag.name), folderId: tags[0]?.id, folderName: tags[0]?.name }; }); state.feed = mode === 'append' ? [...enriched, ...state.feed.filter((story) => !enriched.some((entry) => entry.url === story.url))] : enriched; state.activeFolder = enriched[0]?.tagIds[0] || 'all'; state.newStoryIds = enriched.map((story) => story.id); state.view = 'library'; save(); render(); setTimeout(() => { state.newStoryIds = []; }, 900); toast(`${enriched.length} ${enriched.length === 1 ? 'story' : 'stories'} saved to your shelf.`); return { topic, tags: [...new Set(enriched.flatMap((story) => story.tagNames))], mode, added: enriched, feedCount: state.feed.length }; }
async function registerWebMcpTools() { if (!document.modelContext?.registerTool || toolsRegistered) return; toolsRegistered = true; const injectTool = { name: 'inject-news-to-feed', title: 'Add web-researched news to 4.0-news', description: 'Create or update a personal topic shelf in 4.0-news with selected web-researched articles. Search fast and favor trustworthy primary reporting published in the last 24–48 hours; a story older than 7 days should only appear when it is essential context, and month-old stories are normally out of scope. Prefer direct source pages, verify publication time, avoid duplicates, and keep the result set concise. Provide imageUrl when a relevant article image is available; otherwise the shelf uses the source site favicon. The app never fetches or opens article links.', inputSchema: { type: 'object', properties: { topic: { type: 'string' }, mode: { type: 'string', enum: ['replace', 'append'] }, stories: { type: 'array', minItems: 1, maxItems: 10, items: { type: 'object', properties: { title: { type: 'string' }, source: { type: 'string' }, url: { type: 'string' }, imageUrl: { type: 'string' }, publishedAt: { type: 'string' }, summary: { type: 'string' }, category: { type: 'string' } }, required: ['title', 'source', 'url'], additionalProperties: false } } }, required: ['topic', 'stories'], additionalProperties: false }, annotations: { untrustedContentHint: true }, execute: async ({ topic, stories, mode = 'replace' }) => injectNews(topic, stories, mode) }; const feedTool = { name: 'get-current-feed', title: 'Read the 4.0-news library', description: 'Read the current sourced stories and topic shelves. This is read-only.', inputSchema: { type: 'object', properties: {}, additionalProperties: false }, annotations: { readOnlyHint: true, untrustedContentHint: true }, execute: async () => ({ stories: state.feed, folders: state.folders, count: state.feed.length }) }; try { await document.modelContext.registerTool(injectTool); await document.modelContext.registerTool(feedTool); state.webmcp = { supported: true, registered: 2 }; render(); } catch (error) { toolsRegistered = false; console.warn('WebMCP registration unavailable:', error); } }
document.addEventListener('click', (event) => { const button = event.target.closest('[data-action]'); if (!button) return; const { action, folder, story } = button.dataset; if (action === 'open-all') { state.activeFolder = 'all'; state.view = 'library'; } if (action === 'open-folder') { state.activeFolder = folder; state.view = 'library'; } if (action === 'open-reader') { state.selectedStoryId = story; state.view = 'reader'; window.scrollTo({ top: 0, behavior: 'smooth' }); } if (action === 'back-to-library') { state.view = 'library'; state.selectedStoryId = null; } if (action === 'increase-font') { state.fontScale = Math.min(1.22, Number((state.fontScale + 0.06).toFixed(2))); save(); } if (action === 'decrease-font') { state.fontScale = Math.max(.88, Number((state.fontScale - 0.06).toFixed(2))); save(); } if (action === 'toggle-theme') { state.readerTheme = state.readerTheme === 'night' ? 'paper' : 'night'; save(); } if (action === 'new-folder') { const name = window.prompt('Name this shelf'); if (name) { const created = ensureFolder(name, false); state.activeFolder = created.id; save(); toast(`Created ${created.name}.`); } } if (action === 'rename-folder') { const current = state.folders.find((entry) => entry.id === folder); const name = current && window.prompt('Rename this shelf', current.name); if (name && current) { current.name = titleFor(name); state.feed.filter((entry) => entry.folderId === current.id).forEach((entry) => { entry.folderName = current.name; }); save(); toast('Shelf renamed.'); } } render(); });
migrateExistingStories();
render();
registerWebMcpTools();
